name: Continuous Deployment

on:
  #push:
    #tags:
      #- "v*.*.*"
  workflow_dispatch:

jobs:  
  publish-crates-io:
    name: Publish on crates.io
    needs: publish-github
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Set the release version
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV      
      - name: Publish the crate
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: |
            --allow-dirty --manifest-path Cargo.toml
            --token ${{ secrets.CARGO_TOKEN }}